//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quick_picture_viewer.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("quick_picture_viewer.languages.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        internal static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date.
        /// </summary>
        internal static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App startup action.
        /// </summary>
        internal static string app_startup_action {
            get {
                return ResourceManager.GetString("app-startup-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        internal static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto zoom.
        /// </summary>
        internal static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture screen.
        /// </summary>
        internal static string capture_screen {
            get {
                return ResourceManager.GetString("capture-screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeters.
        /// </summary>
        internal static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on app startup.
        /// </summary>
        internal static string check_for_updates_on_startup {
            get {
                return ResourceManager.GetString("check-for-updates-on-startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkerboard background.
        /// </summary>
        internal static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color.
        /// </summary>
        internal static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy original file.
        /// </summary>
        internal static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this image.
        /// </summary>
        internal static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file could not be found.
        /// </summary>
        internal static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDS/TGA memory error.
        /// </summary>
        internal static string dds_memory_error {
            get {
                return ResourceManager.GetString("dds-memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk size.
        /// </summary>
        internal static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string do_nothing {
            get {
                return ResourceManager.GetString("do-nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragged image.
        /// </summary>
        internal static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        internal static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string external {
            get {
                return ResourceManager.GetString("external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite external app.
        /// </summary>
        internal static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied to clipboard.
        /// </summary>
        internal static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File properties.
        /// </summary>
        internal static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reloaded.
        /// </summary>
        internal static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontal.
        /// </summary>
        internal static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertical.
        /// </summary>
        internal static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameless mode.
        /// </summary>
        internal static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From clipboard.
        /// </summary>
        internal static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path.
        /// </summary>
        internal static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cursor in fullscreen.
        /// </summary>
        internal static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copied to clipboard.
        /// </summary>
        internal static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image info.
        /// </summary>
        internal static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image pasted from clipboard.
        /// </summary>
        internal static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        internal static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow.
        /// </summary>
        internal static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megapixels.
        /// </summary>
        internal static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        internal static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string mouse {
            get {
                return ResourceManager.GetString("mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file to the Recycle Bin.
        /// </summary>
        internal static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window.
        /// </summary>
        internal static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in folder.
        /// </summary>
        internal static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in 1 second.
        /// </summary>
        internal static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in {0} seconds.
        /// </summary>
        internal static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        internal static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to open.
        /// </summary>
        internal static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder.
        /// </summary>
        internal static string no_folder {
            get {
                return ResourceManager.GetString("no-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not saved.
        /// </summary>
        internal static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with external app.
        /// </summary>
        internal static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose app to open.
        /// </summary>
        internal static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with custom app.
        /// </summary>
        internal static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with default app.
        /// </summary>
        internal static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        internal static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste image.
        /// </summary>
        internal static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture in picture.
        /// </summary>
        internal static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        internal static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open an image to view or edit.
        /// </summary>
        internal static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to exit fullscreen mode.
        /// </summary>
        internal static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image in folder.
        /// </summary>
        internal static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print / Export to PDF.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print size.
        /// </summary>
        internal static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file.
        /// </summary>
        internal static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App restart required.
        /// </summary>
        internal static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow.
        /// </summary>
        internal static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 180°.
        /// </summary>
        internal static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate counter-clockwise.
        /// </summary>
        internal static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate clockwise.
        /// </summary>
        internal static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string screenshot {
            get {
                return ResourceManager.GetString("screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as desktop background.
        /// </summary>
        internal static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file in explorer.
        /// </summary>
        internal static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show slideshow counter.
        /// </summary>
        internal static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        internal static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unsaved data will be lost. Are you sure you want to close the application?.
        /// </summary>
        internal static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this file to the Recyble Bin?.
        /// </summary>
        internal static string sure_move_to_trash {
            get {
                return ResourceManager.GetString("sure-move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching time.
        /// </summary>
        internal static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated by.
        /// </summary>
        internal static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        internal static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language:.
        /// </summary>
        internal static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open DDS or TGA file.
        /// </summary>
        internal static string unable_open_dds {
            get {
                return ResourceManager.GetString("unable-open-dds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open SVG file.
        /// </summary>
        internal static string unable_open_svg {
            get {
                return ResourceManager.GetString("unable-open-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open this file.
        /// </summary>
        internal static string unable_to_open_file {
            get {
                return ResourceManager.GetString("unable-to-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run external app.
        /// </summary>
        internal static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unsaved data will be lost. Are you sure you want to open new image?.
        /// </summary>
        internal static string unsaved_data_lost {
            get {
                return ResourceManager.GetString("unsaved-data-lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string updates {
            get {
                return ResourceManager.GetString("updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update manager.
        /// </summary>
        internal static string updator {
            get {
                return ResourceManager.GetString("updator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system setting.
        /// </summary>
        internal static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel to zoom (No {0}).
        /// </summary>
        internal static string wheel_to_zoom {
            get {
                return ResourceManager.GetString("wheel-to-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to actual size.
        /// </summary>
        internal static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
