//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickPictureViewerPlus.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_hr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_hr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickPictureViewerPlus.languages.lang_hr", typeof(lang_hr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programu.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve datoteke.
        /// </summary>
        public static string all_files {
            get {
                return ResourceManager.GetString("all-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi formati slika.
        /// </summary>
        public static string all_image_formats {
            get {
                return ResourceManager.GetString("all-image-formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvijek na vrhu.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perolaki, svestrani preglednik slika za Windows. Najbolja zamjena za zadani preglednik slika u Windowsu..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacija je ažurna!.
        /// </summary>
        public static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radnje kod pokretanja aplikacije.
        /// </summary>
        public static string app_startup_actions {
            get {
                return ResourceManager.GetString("app-startup-actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omjer slike.
        /// </summary>
        public static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatski.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatska veličina.
        /// </summary>
        public static string auto_size {
            get {
                return ResourceManager.GetString("auto-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatski zum.
        /// </summary>
        public static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozadinska boja.
        /// </summary>
        public static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dno.
        /// </summary>
        public static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledaj.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledaj s Quick Picture Viewerom.
        /// </summary>
        public static string browse_folder_with_qpv {
            get {
                return ResourceManager.GetString("browse-folder-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledaj priključke.
        /// </summary>
        public static string browse_for_plugins {
            get {
                return ResourceManager.GetString("browse-for-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sredina.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centriraj sliku.
        /// </summary>
        public static string center_image {
            get {
                return ResourceManager.GetString("center-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimetara.
        /// </summary>
        public static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni transparentnost prozora.
        /// </summary>
        public static string change_window_opacity {
            get {
                return ResourceManager.GetString("change-window-opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traži ažuriranja aplikacije.
        /// </summary>
        public static string check_for_app_updates {
            get {
                return ResourceManager.GetString("check-for-app-updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šahovnička pozadina.
        /// </summary>
        public static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi boju.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi smještaj.
        /// </summary>
        public static string choose_fit {
            get {
                return ResourceManager.GetString("choose-fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Očisti.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarez.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompresija.
        /// </summary>
        public static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontekstni izbornik.
        /// </summary>
        public static string context_menu {
            get {
                return ResourceManager.GetString("context-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da biste promijenili opcije kontekstnog izbornika, morate pokrenuti aplikaciju kao administrator..
        /// </summary>
        public static string context_menu_notice {
            get {
                return ResourceManager.GetString("context-menu-notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiraj.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiraj izvornu datoteku.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiraj ovu sliku.
        /// </summary>
        public static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stvoreno.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stvorio/la.
        /// </summary>
        public static string created_by {
            get {
                return ResourceManager.GetString("created-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obreži.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna datoteka nije pronađena.
        /// </summary>
        public static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izreži.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamno.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši datoteku.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši priključak.
        /// </summary>
        public static string delete_plugin {
            get {
                return ResourceManager.GetString("delete-plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigurno želite ukloniti priključak??.
        /// </summary>
        public static string delete_plugin_warning {
            get {
                return ResourceManager.GetString("delete-plugin-warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veličina na disku.
        /// </summary>
        public static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemoj spremiti.
        /// </summary>
        public static string dont_save {
            get {
                return ResourceManager.GetString("dont-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preuzimanje ažuriranja....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povućena slika.
        /// </summary>
        public static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi sliku.
        /// </summary>
        public static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi polje odabira.
        /// </summary>
        public static string edit_selection {
            get {
                return ResourceManager.GetString("edit-selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efekti.
        /// </summary>
        public static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite {0} za izlaz iz aplikacije.
        /// </summary>
        public static string esc_to_exit {
            get {
                return ResourceManager.GetString("esc-to-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izađi iz načina slike u slici.
        /// </summary>
        public static string exit_picture_in_picture {
            get {
                return ResourceManager.GetString("exit-picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstenzija.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena vanjska aplikacija.
        /// </summary>
        public static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka kopirana u međuspremnik.
        /// </summary>
        public static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka premještena u koš za smeće.
        /// </summary>
        public static string file_moved_to_trash {
            get {
                return ResourceManager.GetString("file-moved-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svojstva datoteke.
        /// </summary>
        public static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka ponovno učitana.
        /// </summary>
        public static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispuni.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prilagodi veličinu.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okreni horizontalno.
        /// </summary>
        public static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okreni vertikalno.
        /// </summary>
        public static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način bez okvira.
        /// </summary>
        public static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iz međuspremnika.
        /// </summary>
        public static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iz &quot;{0}&quot;.
        /// </summary>
        public static string from_format {
            get {
                return ResourceManager.GetString("from-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puna putanja.
        /// </summary>
        public static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puni zaslon.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži kursor u punom zaslonu.
        /// </summary>
        public static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visina.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomozite nam prevesti ovu aplikaciju.
        /// </summary>
        public static string help_us_translate_app {
            get {
                return ResourceManager.GetString("help-us-translate-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika kopirana u međuspremnik.
        /// </summary>
        public static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o slici.
        /// </summary>
        public static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika zalijepljena iz međuspremnika.
        /// </summary>
        public static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inča.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miš i tipkovnica.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instaliraj sada.
        /// </summary>
        public static string install_now {
            get {
                return ResourceManager.GetString("install-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontalno.
        /// </summary>
        public static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontalno.
        /// </summary>
        public static string landscape_orientation {
            get {
                return ResourceManager.GetString("landscape-orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijevo.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijeva strelica.
        /// </summary>
        public static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svijestlo.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadrži omjer slike.
        /// </summary>
        public static string maintain_aspect_ratio {
            get {
                return ResourceManager.GetString("maintain-aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granice margine.
        /// </summary>
        public static string margin_bounds {
            get {
                return ResourceManager.GetString("margin-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margine.
        /// </summary>
        public static string margins {
            get {
                return ResourceManager.GetString("margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megapiskela.
        /// </summary>
        public static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška memorije.
        /// </summary>
        public static string memory_error {
            get {
                return ResourceManager.GetString("memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijenjeno.
        /// </summary>
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Više opcija.
        /// </summary>
        public static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Više priključaka.
        /// </summary>
        public static string more_plugins {
            get {
                return ResourceManager.GetString("more-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radnja pomicanja kotačića miša.
        /// </summary>
        public static string mouse_wheel_action {
            get {
                return ResourceManager.GetString("mouse-wheel-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premjesti datoteku u koš za smeće.
        /// </summary>
        public static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupna je nova verzija!.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new-version-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi prozor.
        /// </summary>
        public static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stvori novi prazni prozor.
        /// </summary>
        public static string new_window_desc {
            get {
                return ResourceManager.GetString("new-window-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeća slika u mapi.
        /// </summary>
        public static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeća slika za 1 sekundu.
        /// </summary>
        public static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeća slika za {0} sekunde/i.
        /// </summary>
        public static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeća/prethodna slika u mapi.
        /// </summary>
        public static string next_prev_image {
            get {
                return ResourceManager.GetString("next-prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema datoteke.
        /// </summary>
        public static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema datoteka za otvaranje.
        /// </summary>
        public static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije spremljeno.
        /// </summary>
        public static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori datoteku u vanjskoj aplikaciji.
        /// </summary>
        public static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori datoteku.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori mapu.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekurzivno otvaraj mapu.
        /// </summary>
        public static string open_recursive {
            get {
                return ResourceManager.GetString("open-recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori s.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite aplikaciju za otvaranje.
        /// </summary>
        public static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori prilagođenu aplikaciju.
        /// </summary>
        public static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori zadanom aplikacijom.
        /// </summary>
        public static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori s Quick Picture Viewerom.
        /// </summary>
        public static string open_with_qpv {
            get {
                return ResourceManager.GetString("open-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvorna veličina.
        /// </summary>
        public static string original_size {
            get {
                return ResourceManager.GetString("original-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalijepi iz međuspremnika.
        /// </summary>
        public static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalijepi sliku.
        /// </summary>
        public static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajno izbriši datoteku.
        /// </summary>
        public static string perm_delete {
            get {
                return ResourceManager.GetString("perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način slike u slici.
        /// </summary>
        public static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to piksela.
        /// </summary>
        public static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvorite sliku za pregledavanje ili uređivanje.
        /// </summary>
        public static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priključak.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravitelj priključcima.
        /// </summary>
        public static string plugin_manager {
            get {
                return ResourceManager.GetString("plugin-manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije pronađena mapa priključaka.
        /// </summary>
        public static string plugin_not_found {
            get {
                return ResourceManager.GetString("plugin-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-stranica priključka.
        /// </summary>
        public static string plugin_website {
            get {
                return ResourceManager.GetString("plugin-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikalno.
        /// </summary>
        public static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretpodešene postavke.
        /// </summary>
        public static string presets {
            get {
                return ResourceManager.GetString("presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite {0} za izlaz iz punog zaslona.
        /// </summary>
        public static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna slika u mapi.
        /// </summary>
        public static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispiši/izvezi u PDF.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracija ispisa.
        /// </summary>
        public static string print_conf {
            get {
                return ResourceManager.GetString("print-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće postaviti margine dokumenta.
        /// </summary>
        public static string print_margins_error {
            get {
                return ResourceManager.GetString("print-margins-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veličina ispisa.
        /// </summary>
        public static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremno za instalaciju.
        /// </summary>
        public static string ready_to_install {
            get {
                return ResourceManager.GetString("ready-to-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovno učitaj datoteku.
        /// </summary>
        public static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovno učitaj popis priključaka.
        /// </summary>
        public static string reload_plugins {
            get {
                return ResourceManager.GetString("reload-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni veličinu SVG-a.
        /// </summary>
        public static string resize_svg {
            get {
                return ResourceManager.GetString("resize-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovno pokreni.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno ponovno pokrenuti aplikaciju.
        /// </summary>
        public static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrati prethodne granice prozora.
        /// </summary>
        public static string restore_last_window_bounds {
            get {
                return ResourceManager.GetString("restore-last-window-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desno.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desna strelica.
        /// </summary>
        public static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotiraj 180°.
        /// </summary>
        public static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotiraj suprotno od kazaljke na satu.
        /// </summary>
        public static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotiraj u smjeru kazaljke na satu.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi kao.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomak gore/dolje.
        /// </summary>
        public static string scroll_up_down {
            get {
                return ResourceManager.GetString("scroll-up-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sekundi.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi sve.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alat za odabir.
        /// </summary>
        public static string selection_tool {
            get {
                return ResourceManager.GetString("selection-tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi kao zadani preglednik slika.
        /// </summary>
        public static string set_as_default_image_viewer {
            get {
                return ResourceManager.GetString("set-as-default-image-viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi kao pozadinu radne površine.
        /// </summary>
        public static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi pozadinu.
        /// </summary>
        public static string set_background {
            get {
                return ResourceManager.GetString("set-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi margine.
        /// </summary>
        public static string set_margins_btn {
            get {
                return ResourceManager.GetString("set-margins-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži datoteku u Exploreru.
        /// </summary>
        public static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži navigacijske strelice.
        /// </summary>
        public static string show_nav_arrows {
            get {
                return ResourceManager.GetString("show-nav-arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži brojač prezentacije.
        /// </summary>
        public static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži statusnu traku.
        /// </summary>
        public static string show_status_bar {
            get {
                return ResourceManager.GetString("show-status-bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži alatnu traku.
        /// </summary>
        public static string show_toolbar {
            get {
                return ResourceManager.GetString("show-toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veličina.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preskoči ovu verziju.
        /// </summary>
        public static string skip_this_version {
            get {
                return ResourceManager.GetString("skip-this-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezentacija.
        /// </summary>
        public static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obuhvati sve.
        /// </summary>
        public static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvadratno.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokretanje.
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razvuci.
        /// </summary>
        public static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi nespremljeni podatci bit će izgubljeni. Sigurno želite zatvoriti aplikaciju?.
        /// </summary>
        public static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigurno želite trajno izbrisati ovu datoteku?.
        /// </summary>
        public static string sure_perm_delete {
            get {
                return ResourceManager.GetString("sure-perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme prebacivanja.
        /// </summary>
        public static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poploči.
        /// </summary>
        public static string tile {
            get {
                return ResourceManager.GetString("tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alati.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrh.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preveo/la.
        /// </summary>
        public static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcije.
        /// </summary>
        public static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik korisničkog sučelja.
        /// </summary>
        public static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće otvoriti datoteku.
        /// </summary>
        public static string unable_open_file {
            get {
                return ResourceManager.GetString("unable-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće otvoriti datoteku, datoteka je preskočena.
        /// </summary>
        public static string unable_open_file_skipped {
            get {
                return ResourceManager.GetString("unable-open-file-skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće pokrenuti vanjsku aplikaciju.
        /// </summary>
        public static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nespremljene promjene.
        /// </summary>
        public static string unsaved_changes {
            get {
                return ResourceManager.GetString("unsaved-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna slika ima nespremljene promjene. Što želite učiniti?.
        /// </summary>
        public static string unsaved_changes_question {
            get {
                return ResourceManager.GetString("unsaved-changes-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodržani format piksela.
        /// </summary>
        public static string unsupported_pixel_format {
            get {
                return ResourceManager.GetString("unsupported-pixel-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje nije uspjelo.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzija {0} Quick Picture Viewera je dostupna, a koristite verziju {1}. Ažurirati sada?.
        /// </summary>
        public static string update_text {
            get {
                return ResourceManager.GetString("update-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje Quick Picture Viewera.
        /// </summary>
        public static string updating_qpv {
            get {
                return ResourceManager.GetString("updating-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koristi postavke sustava.
        /// </summary>
        public static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzija.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Što je novo?.
        /// </summary>
        public static string whats_new {
            get {
                return ResourceManager.GetString("whats-new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Širina.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povećaj prikaz.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povećaj/smanji prikaz.
        /// </summary>
        public static string zoom_in_out {
            get {
                return ResourceManager.GetString("zoom-in-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smanji prikaz.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zumiraj na stvarnu veličinu.
        /// </summary>
        public static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
