//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickPictureViewerPlus.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickPictureViewerPlus.languages.lang_de", typeof(lang_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien anzeigen.
        /// </summary>
        public static string all_files {
            get {
                return ResourceManager.GetString("all-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Datei-Formate anzeigen.
        /// </summary>
        public static string all_image_formats {
            get {
                return ResourceManager.GetString("all-image-formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App immer im Vordergrund verwenden.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichtgewichtiger, vielseitiger Desktop-Bildbetrachter für Windows. Der beste Ersatz für den voreingestellten Windows Bildbetrachter..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ist auf dem neuesten Stand!.
        /// </summary>
        public static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Aktionen während des Starts.
        /// </summary>
        public static string app_startup_actions {
            get {
                return ResourceManager.GetString("app-startup-actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenverhältnis.
        /// </summary>
        public static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Grösse.
        /// </summary>
        public static string auto_size {
            get {
                return ResourceManager.GetString("auto-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatischer Zoom.
        /// </summary>
        public static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrundfarbe.
        /// </summary>
        public static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unterster Stelle.
        /// </summary>
        public static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner mit QPV durchsuchen.
        /// </summary>
        public static string browse_folder_with_qpv {
            get {
                return ResourceManager.GetString("browse-folder-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Plugins.
        /// </summary>
        public static string browse_for_plugins {
            get {
                return ResourceManager.GetString("browse-for-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitte.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild zentrieren.
        /// </summary>
        public static string center_image {
            get {
                return ResourceManager.GetString("center-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentimeter.
        /// </summary>
        public static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deckkraft des Fenster ändern.
        /// </summary>
        public static string change_window_opacity {
            get {
                return ResourceManager.GetString("change-window-opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfe nach App-Updates.
        /// </summary>
        public static string check_for_app_updates {
            get {
                return ResourceManager.GetString("check-for-app-updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schachbrett Hintergrund.
        /// </summary>
        public static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle eine Farbe.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie eine Passform aus.
        /// </summary>
        public static string choose_fit {
            get {
                return ResourceManager.GetString("choose-fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeren.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komma.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komprimierung.
        /// </summary>
        public static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontext Menü.
        /// </summary>
        public static string context_menu {
            get {
                return ResourceManager.GetString("context-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um das Kontextmenü zu ändern, muss die App mit Administratorberechtigung ausgeführt werden..
        /// </summary>
        public static string context_menu_notice {
            get {
                return ResourceManager.GetString("context-menu-notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originaldatei kopieren.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Bild kopieren.
        /// </summary>
        public static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        public static string created_by {
            get {
                return ResourceManager.GetString("created-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuschneiden.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Datei konnte nicht gefunden werden.
        /// </summary>
        public static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnitt.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkel.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Datei löschen.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin löschen.
        /// </summary>
        public static string delete_plugin {
            get {
                return ResourceManager.GetString("delete-plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie dieses Plugin wirklich löschen?.
        /// </summary>
        public static string delete_plugin_warning {
            get {
                return ResourceManager.GetString("delete-plugin-warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festplattengröße.
        /// </summary>
        public static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht speichern.
        /// </summary>
        public static string dont_save {
            get {
                return ResourceManager.GetString("dont-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update wird heruntergeladen....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehen des Bildes.
        /// </summary>
        public static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild bearbeiten.
        /// </summary>
        public static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahlbereich bearbeiten.
        /// </summary>
        public static string edit_selection {
            get {
                return ResourceManager.GetString("edit-selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effekte.
        /// </summary>
        public static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Esc&quot; zum beenden der App.
        /// </summary>
        public static string esc_to_exit {
            get {
                return ResourceManager.GetString("esc-to-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden des Bild-in-Bild-Modus .
        /// </summary>
        public static string exit_picture_in_picture {
            get {
                return ResourceManager.GetString("exit-picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erweiterungen.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QPV als bevorzugte Anwendung verwenden.
        /// </summary>
        public static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei in die Zwischenablage kopiert.
        /// </summary>
        public static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei in den Papierkorb verschoben.
        /// </summary>
        public static string file_moved_to_trash {
            get {
                return ResourceManager.GetString("file-moved-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei Eigenschaften.
        /// </summary>
        public static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei wird neu geladen.
        /// </summary>
        public static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausfüllen.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passend.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal spiegeln.
        /// </summary>
        public static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikal spiegeln.
        /// </summary>
        public static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmenloser-Modus.
        /// </summary>
        public static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus der Zwischenablage.
        /// </summary>
        public static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von welchem Format?.
        /// </summary>
        public static string from_format {
            get {
                return ResourceManager.GetString("from-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollständiger Dateipfad.
        /// </summary>
        public static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollbildmodus.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauszeiger in Vollbildmodus anzeigen?.
        /// </summary>
        public static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilf uns die App zu übersetzen.
        /// </summary>
        public static string help_us_translate_app {
            get {
                return ResourceManager.GetString("help-us-translate-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild in die Zwischenablage kopiert.
        /// </summary>
        public static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild-Informationen.
        /// </summary>
        public static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild aus der Zwischenablage eingefügt.
        /// </summary>
        public static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoll.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maus und Tastatur.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt installieren.
        /// </summary>
        public static string install_now {
            get {
                return ResourceManager.GetString("install-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbildung.
        /// </summary>
        public static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbildungsausrichtung.
        /// </summary>
        public static string landscape_orientation {
            get {
                return ResourceManager.GetString("landscape-orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linke Pfeil Taste.
        /// </summary>
        public static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beleuchtung.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalisierung.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenverhältnis beibehalten.
        /// </summary>
        public static string maintain_aspect_ratio {
            get {
                return ResourceManager.GetString("maintain-aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randbegrenzungen.
        /// </summary>
        public static string margin_bounds {
            get {
                return ResourceManager.GetString("margin-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenränder.
        /// </summary>
        public static string margins {
            get {
                return ResourceManager.GetString("margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megapixels..
        /// </summary>
        public static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler.
        /// </summary>
        public static string memory_error {
            get {
                return ResourceManager.GetString("memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geändert..
        /// </summary>
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Optionen.
        /// </summary>
        public static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Plugins.
        /// </summary>
        public static string more_plugins {
            get {
                return ResourceManager.GetString("more-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mausrad-Scroll-Aktion.
        /// </summary>
        public static string mouse_wheel_action {
            get {
                return ResourceManager.GetString("mouse-wheel-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei löschen.
        /// </summary>
        public static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine neue Version von &quot;Quick Picture Viewer&quot; ist verfügbar..
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new-version-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Fenster öffnen.
        /// </summary>
        public static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues leeres Fenster erzeugen.
        /// </summary>
        public static string new_window_desc {
            get {
                return ResourceManager.GetString("new-window-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes Bild im Ordner anzeigen.
        /// </summary>
        public static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes Bild erscheint in 1 Sekunde.
        /// </summary>
        public static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes Bild erscheint in {0} Sekunden.
        /// </summary>
        public static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächstes/Vorhergehendes Bild im Ordner anzeigen.
        /// </summary>
        public static string next_prev_image {
            get {
                return ResourceManager.GetString("next-prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datei.
        /// </summary>
        public static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Dateien zum Öffnen.
        /// </summary>
        public static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei nicht gespeichert.
        /// </summary>
        public static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei mit externer App öffnen.
        /// </summary>
        public static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei öffnen.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner öffnen.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis rekursiv öffnen.
        /// </summary>
        public static string open_recursive {
            get {
                return ResourceManager.GetString("open-recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen mit.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App zum Öffnen auswählen.
        /// </summary>
        public static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit benutzerdefinierter App öffnen.
        /// </summary>
        public static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Standard-App öffnen.
        /// </summary>
        public static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Quick Picture Viewer öffnen.
        /// </summary>
        public static string open_with_qpv {
            get {
                return ResourceManager.GetString("open-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Grösse des Bildes.
        /// </summary>
        public static string original_size {
            get {
                return ResourceManager.GetString("original-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus Zwischenablage einfügen.
        /// </summary>
        public static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild einfügen.
        /// </summary>
        public static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei dauerhaft löschen.
        /// </summary>
        public static string perm_delete {
            get {
                return ResourceManager.GetString("perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild-in-Bild-Modus.
        /// </summary>
        public static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel/Bildpunkte.
        /// </summary>
        public static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte öffnen Sie ein Bild um es zu Betrachten oder zu Bearbeiten.
        /// </summary>
        public static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin-Verwaltung.
        /// </summary>
        public static string plugin_manager {
            get {
                return ResourceManager.GetString("plugin-manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin-Verzeichnis wurde nicht gefunden.
        /// </summary>
        public static string plugin_not_found {
            get {
                return ResourceManager.GetString("plugin-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin-Webseite.
        /// </summary>
        public static string plugin_website {
            get {
                return ResourceManager.GetString("plugin-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochformat.
        /// </summary>
        public static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voreinstellungen.
        /// </summary>
        public static string presets {
            get {
                return ResourceManager.GetString("presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücken Sie {0}, um den Vollbildmodus zu verlassen.
        /// </summary>
        public static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorheriges Bild in Verzeichnis.
        /// </summary>
        public static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken/Exportieren als PDF.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckkonfiguration.
        /// </summary>
        public static string print_conf {
            get {
                return ResourceManager.GetString("print-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentenränder können nicht eingestellt werden.
        /// </summary>
        public static string print_margins_error {
            get {
                return ResourceManager.GetString("print-margins-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druck-Grösse.
        /// </summary>
        public static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereit zu installieren.
        /// </summary>
        public static string ready_to_install {
            get {
                return ResourceManager.GetString("ready-to-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei neu laden.
        /// </summary>
        public static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin-Liste neu laden.
        /// </summary>
        public static string reload_plugins {
            get {
                return ResourceManager.GetString("reload-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe der SVG ändern .
        /// </summary>
        public static string resize_svg {
            get {
                return ResourceManager.GetString("resize-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auflösung.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustart der App ist erforderlich.
        /// </summary>
        public static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Fensterbegrenzung wiederherstellen.
        /// </summary>
        public static string restore_last_window_bounds {
            get {
                return ResourceManager.GetString("restore-last-window-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechts.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechte Pfeil Taste.
        /// </summary>
        public static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um 180° drehen.
        /// </summary>
        public static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegen den Uhrzeigersinn drehen.
        /// </summary>
        public static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Uhrzeigersinn drehen.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern unter.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben / unten blättern/scrollen.
        /// </summary>
        public static string scroll_up_down {
            get {
                return ResourceManager.GetString("scroll-up-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunden.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Alle.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl-Werkzeug.
        /// </summary>
        public static string selection_tool {
            get {
                return ResourceManager.GetString("selection-tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Standard-Bildbetrachter festlegen.
        /// </summary>
        public static string set_as_default_image_viewer {
            get {
                return ResourceManager.GetString("set-as-default-image-viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild als Desktophintergrund festlegen.
        /// </summary>
        public static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund festlegen.
        /// </summary>
        public static string set_background {
            get {
                return ResourceManager.GetString("set-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenränder einstellen.
        /// </summary>
        public static string set_margins_btn {
            get {
                return ResourceManager.GetString("set-margins-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei im Explorer zeigen.
        /// </summary>
        public static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigationspfeile anzeigen.
        /// </summary>
        public static string show_nav_arrows {
            get {
                return ResourceManager.GetString("show-nav-arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diashowzähler anzeigen.
        /// </summary>
        public static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusleiste anzeigen.
        /// </summary>
        public static string show_status_bar {
            get {
                return ResourceManager.GetString("show-status-bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolleiste anzeigen.
        /// </summary>
        public static string show_toolbar {
            get {
                return ResourceManager.GetString("show-toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grösse.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Version überspringen.
        /// </summary>
        public static string skip_this_version {
            get {
                return ResourceManager.GetString("skip-this-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diashow.
        /// </summary>
        public static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereich.
        /// </summary>
        public static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratisch.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup/Inbetriebnahme.
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strecken.
        /// </summary>
        public static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle nicht gespeicherten Daten gehen verloren. Sind Sie sicher, dass Sie diese Anwendung schließen wollen?.
        /// </summary>
        public static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diese Datei wirklich dauerhaft löschen?.
        /// </summary>
        public static string sure_perm_delete {
            get {
                return ResourceManager.GetString("sure-perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Schaltdauer beträgt.
        /// </summary>
        public static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kachel.
        /// </summary>
        public static string tile {
            get {
                return ResourceManager.GetString("tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeuge.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oben.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzt von.
        /// </summary>
        public static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        public static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache der Benutzeroberfläche.
        /// </summary>
        public static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei kann nicht geöffnet werden.
        /// </summary>
        public static string unable_open_file {
            get {
                return ResourceManager.GetString("unable-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei kann nicht geöffnet werden, Datei übersprungen.
        /// </summary>
        public static string unable_open_file_skipped {
            get {
                return ResourceManager.GetString("unable-open-file-skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe Anwendung kann nicht ausgeführt werden.
        /// </summary>
        public static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gespeicherte Änderungen.
        /// </summary>
        public static string unsaved_changes {
            get {
                return ResourceManager.GetString("unsaved-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das aktuelle Bild hat nicht gespeicherte Änderungen. Was würden Sie gerne tun?.
        /// </summary>
        public static string unsaved_changes_question {
            get {
                return ResourceManager.GetString("unsaved-changes-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht unterstütztes Pixelformat/Bildpunktformat.
        /// </summary>
        public static string unsupported_pixel_format {
            get {
                return ResourceManager.GetString("unsupported-pixel-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung fehlgeschlagen.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine neuere Version {0} von Quick Picture Viewer ist verfügbar. Wollen Sie Ihre ältere Version {1} auf die neuste aktualisieren?.
        /// </summary>
        public static string update_text {
            get {
                return ResourceManager.GetString("update-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren des Quick Picture Viewers.
        /// </summary>
        public static string updating_qpv {
            get {
                return ResourceManager.GetString("updating-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemeinstellungen verwenden.
        /// </summary>
        public static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführung.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was gibt es neues?.
        /// </summary>
        public static string whats_new {
            get {
                return ResourceManager.GetString("whats-new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergrößern.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild vergrößern/Heranzoomen.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild vergrößern/verkleinern.
        /// </summary>
        public static string zoom_in_out {
            get {
                return ResourceManager.GetString("zoom-in-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild verkleinern/Hinauszoomen.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild auf tatsächliche Größe setzen.
        /// </summary>
        public static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
