//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickPictureViewerPlus.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickPictureViewerPlus.languages.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О приложении.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы.
        /// </summary>
        public static string all_files {
            get {
                return ResourceManager.GetString("all-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все форматы изображений.
        /// </summary>
        public static string all_image_formats {
            get {
                return ResourceManager.GetString("all-image-formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверх всех окон.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкая и универсальная программа для просмотра изображений для компьютеров на Windows. Лучшая замена стандартной программе просмотра фотографий Windows..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение использует актуальную версию!.
        /// </summary>
        public static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия при запуске приложения.
        /// </summary>
        public static string app_startup_actions {
            get {
                return ResourceManager.GetString("app-startup-actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соотношение.
        /// </summary>
        public static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string auto_size {
            get {
                return ResourceManager.GetString("auto-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто масштаб.
        /// </summary>
        public static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона.
        /// </summary>
        public static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снизу.
        /// </summary>
        public static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку с помощью Quick Picture Viewer.
        /// </summary>
        public static string browse_folder_with_qpv {
            get {
                return ResourceManager.GetString("browse-folder-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти плагины.
        /// </summary>
        public static string browse_for_plugins {
            get {
                return ResourceManager.GetString("browse-for-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центрировать.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центрировать изображение.
        /// </summary>
        public static string center_image {
            get {
                return ResourceManager.GetString("center-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сантиметров.
        /// </summary>
        public static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить прозрачность окна.
        /// </summary>
        public static string change_window_opacity {
            get {
                return ResourceManager.GetString("change-window-opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить наличие обновлений.
        /// </summary>
        public static string check_for_app_updates {
            get {
                return ResourceManager.GetString("check-for-app-updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон шахматной доски.
        /// </summary>
        public static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать цвет.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим размещения.
        /// </summary>
        public static string choose_fit {
            get {
                return ResourceManager.GetString("choose-fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запятая.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сжатие.
        /// </summary>
        public static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контекстное меню.
        /// </summary>
        public static string context_menu {
            get {
                return ResourceManager.GetString("context-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы изменить параметры контекстного меню, вам необходимо запустить приложение с правами Администратора.
        /// </summary>
        public static string context_menu_notice {
            get {
                return ResourceManager.GetString("context-menu-notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать открытый файл.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать изображение.
        /// </summary>
        public static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчик.
        /// </summary>
        public static string created_by {
            get {
                return ResourceManager.GetString("created-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрезать.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий файл не найден.
        /// </summary>
        public static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёмная.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить файл.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить плагин.
        /// </summary>
        public static string delete_plugin {
            get {
                return ResourceManager.GetString("delete-plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить плагин?.
        /// </summary>
        public static string delete_plugin_warning {
            get {
                return ResourceManager.GetString("delete-plugin-warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на диске.
        /// </summary>
        public static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранять.
        /// </summary>
        public static string dont_save {
            get {
                return ResourceManager.GetString("dont-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка обновления....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащенное изображение.
        /// </summary>
        public static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать область выделения.
        /// </summary>
        public static string edit_selection {
            get {
                return ResourceManager.GetString("edit-selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эффекты.
        /// </summary>
        public static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите {0}, чтобы выйти из приложения.
        /// </summary>
        public static string esc_to_exit {
            get {
                return ResourceManager.GetString("esc-to-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из режима &quot;Картинка в картинке&quot;.
        /// </summary>
        public static string exit_picture_in_picture {
            get {
                return ResourceManager.GetString("exit-picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширение.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимое стороннее приложение.
        /// </summary>
        public static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл скопирован в буфер обмена.
        /// </summary>
        public static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл перемещен в корзину.
        /// </summary>
        public static string file_moved_to_trash {
            get {
                return ResourceManager.GetString("file-moved-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства файла.
        /// </summary>
        public static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл переоткрыт.
        /// </summary>
        public static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подогнать.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отразить по горизонтали.
        /// </summary>
        public static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отразить по вертикали.
        /// </summary>
        public static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безрамочный режим.
        /// </summary>
        public static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С буфера обмена.
        /// </summary>
        public static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено из &quot;{0}&quot;.
        /// </summary>
        public static string from_format {
            get {
                return ResourceManager.GetString("from-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный путь.
        /// </summary>
        public static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На весь экран.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать курсор в полноэкранном режиме.
        /// </summary>
        public static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помогите нам перевести это приложение.
        /// </summary>
        public static string help_us_translate_app {
            get {
                return ResourceManager.GetString("help-us-translate-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение скопировано в буфер обмена.
        /// </summary>
        public static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об изображении.
        /// </summary>
        public static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение получено с буфера обмена.
        /// </summary>
        public static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дюймов.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клавиатура и мышь.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить сейчас.
        /// </summary>
        public static string install_now {
            get {
                return ResourceManager.GetString("install-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомная.
        /// </summary>
        public static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомная ориентация.
        /// </summary>
        public static string landscape_orientation {
            get {
                return ResourceManager.GetString("landscape-orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слева.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелка влево.
        /// </summary>
        public static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локализация.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранять пропорции.
        /// </summary>
        public static string maintain_aspect_ratio {
            get {
                return ResourceManager.GetString("maintain-aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсупить от краев.
        /// </summary>
        public static string margin_bounds {
            get {
                return ResourceManager.GetString("margin-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отступы.
        /// </summary>
        public static string margins {
            get {
                return ResourceManager.GetString("margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мегапикселей.
        /// </summary>
        public static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка памяти .
        /// </summary>
        public static string memory_error {
            get {
                return ResourceManager.GetString("memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минус.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменен.
        /// </summary>
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще.
        /// </summary>
        public static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше плагинов.
        /// </summary>
        public static string more_plugins {
            get {
                return ResourceManager.GetString("more-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие на колёсико мыши.
        /// </summary>
        public static string mouse_wheel_action {
            get {
                return ResourceManager.GetString("mouse-wheel-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переместить файл в Корзину.
        /// </summary>
        public static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно новое обновление!.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new-version-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое окно.
        /// </summary>
        public static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новое пустое окно.
        /// </summary>
        public static string new_window_desc {
            get {
                return ResourceManager.GetString("new-window-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий файл в папке.
        /// </summary>
        public static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующее изображение через 1 секунду.
        /// </summary>
        public static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующее изображение через {0} секунд.
        /// </summary>
        public static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий / предыдущий файл в папке.
        /// </summary>
        public static string next_prev_image {
            get {
                return ResourceManager.GetString("next-prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файла.
        /// </summary>
        public static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файлов для открытия.
        /// </summary>
        public static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранено.
        /// </summary>
        public static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл с помощью стороннего приложения.
        /// </summary>
        public static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку рекурсивно.
        /// </summary>
        public static string open_recursive {
            get {
                return ResourceManager.GetString("open-recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть с помощью.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать приложение.
        /// </summary>
        public static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть приложением пользователя.
        /// </summary>
        public static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть сторонним приложением по-умолчанию.
        /// </summary>
        public static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть с помощью Quick Picture Viewer.
        /// </summary>
        public static string open_with_qpv {
            get {
                return ResourceManager.GetString("open-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный.
        /// </summary>
        public static string original_size {
            get {
                return ResourceManager.GetString("original-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить с буфера обмена.
        /// </summary>
        public static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить файл безвозвратно.
        /// </summary>
        public static string perm_delete {
            get {
                return ResourceManager.GetString("perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим &quot;Картинка в картинке&quot;.
        /// </summary>
        public static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пикселей.
        /// </summary>
        public static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте изображение для просмотра или редактирования.
        /// </summary>
        public static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плагин.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер плагинов.
        /// </summary>
        public static string plugin_manager {
            get {
                return ResourceManager.GetString("plugin-manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директория плагина не найдена.
        /// </summary>
        public static string plugin_not_found {
            get {
                return ResourceManager.GetString("plugin-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вебсайт плагина.
        /// </summary>
        public static string plugin_website {
            get {
                return ResourceManager.GetString("plugin-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плюс.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Портретная.
        /// </summary>
        public static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пресеты.
        /// </summary>
        public static string presets {
            get {
                return ResourceManager.GetString("presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите {0}, чтобы выйти из полноэкранного режима.
        /// </summary>
        public static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий файл в папке.
        /// </summary>
        public static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать / Экспорт в PDF.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры печати.
        /// </summary>
        public static string print_conf {
            get {
                return ResourceManager.GetString("print-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось установить отступы документа.
        /// </summary>
        public static string print_margins_error {
            get {
                return ResourceManager.GetString("print-margins-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер печати.
        /// </summary>
        public static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все готово к установке.
        /// </summary>
        public static string ready_to_install {
            get {
                return ResourceManager.GetString("ready-to-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переоткрыть файл.
        /// </summary>
        public static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить список плагинов.
        /// </summary>
        public static string reload_plugins {
            get {
                return ResourceManager.GetString("reload-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить размер SVG.
        /// </summary>
        public static string resize_svg {
            get {
                return ResourceManager.GetString("resize-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапустить.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется перезапуск приложения.
        /// </summary>
        public static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить последние границы окна.
        /// </summary>
        public static string restore_last_window_bounds {
            get {
                return ResourceManager.GetString("restore-last-window-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справа.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелка вправо.
        /// </summary>
        public static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернуть на 180°.
        /// </summary>
        public static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернуть против часовой стрелки.
        /// </summary>
        public static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернуть по часовой стрелке.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прокрутка вверх / вниз.
        /// </summary>
        public static string scroll_up_down {
            get {
                return ResourceManager.GetString("scroll-up-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить все.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструмент выделения.
        /// </summary>
        public static string selection_tool {
            get {
                return ResourceManager.GetString("selection-tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать приложением по умолчанию.
        /// </summary>
        public static string set_as_default_image_viewer {
            get {
                return ResourceManager.GetString("set-as-default-image-viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фоновым изображением рабочего стола.
        /// </summary>
        public static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить как обои.
        /// </summary>
        public static string set_background {
            get {
                return ResourceManager.GetString("set-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить отступы.
        /// </summary>
        public static string set_margins_btn {
            get {
                return ResourceManager.GetString("set-margins-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать файл в папке.
        /// </summary>
        public static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать стрелки навигации.
        /// </summary>
        public static string show_nav_arrows {
            get {
                return ResourceManager.GetString("show-nav-arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать счётчик слайдшоу.
        /// </summary>
        public static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать статус бар.
        /// </summary>
        public static string show_status_bar {
            get {
                return ResourceManager.GetString("show-status-bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать панель инструментов.
        /// </summary>
        public static string show_toolbar {
            get {
                return ResourceManager.GetString("show-toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить эту версию.
        /// </summary>
        public static string skip_this_version {
            get {
                return ResourceManager.GetString("skip-this-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слайдшоу.
        /// </summary>
        public static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перекрывать.
        /// </summary>
        public static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разтянуть.
        /// </summary>
        public static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все несохраненные изменения будут утеряны. Вы уверены, что хотите закрыть приложение?.
        /// </summary>
        public static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите безвозвратно удалить этот файл?.
        /// </summary>
        public static string sure_perm_delete {
            get {
                return ResourceManager.GetString("sure-perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время переключения.
        /// </summary>
        public static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитка.
        /// </summary>
        public static string tile {
            get {
                return ResourceManager.GetString("tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструменты.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сверху.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы перевода.
        /// </summary>
        public static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опции.
        /// </summary>
        public static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык интерфейса.
        /// </summary>
        public static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно открыть файл.
        /// </summary>
        public static string unable_open_file {
            get {
                return ResourceManager.GetString("unable-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно открыть файл, файл пропущен.
        /// </summary>
        public static string unable_open_file_skipped {
            get {
                return ResourceManager.GetString("unable-open-file-skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось запустить стороннее приложение.
        /// </summary>
        public static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несохраненные изменения.
        /// </summary>
        public static string unsaved_changes {
            get {
                return ResourceManager.GetString("unsaved-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее изображение имеет несохраненные изменения. Чтобы Вы хотели сделать?.
        /// </summary>
        public static string unsaved_changes_question {
            get {
                return ResourceManager.GetString("unsaved-changes-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый формат пикселей.
        /// </summary>
        public static string unsupported_pixel_format {
            get {
                return ResourceManager.GetString("unsupported-pixel-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой обновления приложения.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна версия {0} для Quick Picture Viewer, вы используете версию {1}, обновить сейчас?.
        /// </summary>
        public static string update_text {
            get {
                return ResourceManager.GetString("update-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление Quick Picture Viewer.
        /// </summary>
        public static string updating_qpv {
            get {
                return ResourceManager.GetString("updating-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать системную настройку.
        /// </summary>
        public static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что нового?.
        /// </summary>
        public static string whats_new {
            get {
                return ResourceManager.GetString("whats-new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштаб.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить масштаб.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить / уменьшить масштаб.
        /// </summary>
        public static string zoom_in_out {
            get {
                return ResourceManager.GetString("zoom-in-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить масштаб.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактический масштаб.
        /// </summary>
        public static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
