//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickPictureViewerPlus.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickPictureViewerPlus.languages.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string all_files {
            get {
                return ResourceManager.GetString("all-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All image formats.
        /// </summary>
        public static string all_image_formats {
            get {
                return ResourceManager.GetString("all-image-formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight, versatile desktop image viewer for Windows. The best replacement for the default Windows photo viewer..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date!.
        /// </summary>
        public static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App startup actions.
        /// </summary>
        public static string app_startup_actions {
            get {
                return ResourceManager.GetString("app-startup-actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        public static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto size.
        /// </summary>
        public static string auto_size {
            get {
                return ResourceManager.GetString("auto-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto zoom.
        /// </summary>
        public static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse with Quick Picture Viewer.
        /// </summary>
        public static string browse_folder_with_qpv {
            get {
                return ResourceManager.GetString("browse-folder-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for plugins.
        /// </summary>
        public static string browse_for_plugins {
            get {
                return ResourceManager.GetString("browse-for-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center image.
        /// </summary>
        public static string center_image {
            get {
                return ResourceManager.GetString("center-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeters.
        /// </summary>
        public static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change window opacity.
        /// </summary>
        public static string change_window_opacity {
            get {
                return ResourceManager.GetString("change-window-opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for app updates.
        /// </summary>
        public static string check_for_app_updates {
            get {
                return ResourceManager.GetString("check-for-app-updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkerboard background.
        /// </summary>
        public static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose color.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a fit.
        /// </summary>
        public static string choose_fit {
            get {
                return ResourceManager.GetString("choose-fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        public static string context_menu {
            get {
                return ResourceManager.GetString("context-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change context menu options you need to run the app with Administrator.
        /// </summary>
        public static string context_menu_notice {
            get {
                return ResourceManager.GetString("context-menu-notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy original file.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this image.
        /// </summary>
        public static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string created_by {
            get {
                return ResourceManager.GetString("created-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file could not be found.
        /// </summary>
        public static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete plugin.
        /// </summary>
        public static string delete_plugin {
            get {
                return ResourceManager.GetString("delete-plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the plugin?.
        /// </summary>
        public static string delete_plugin_warning {
            get {
                return ResourceManager.GetString("delete-plugin-warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk size.
        /// </summary>
        public static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string dont_save {
            get {
                return ResourceManager.GetString("dont-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragged image.
        /// </summary>
        public static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        public static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selection area.
        /// </summary>
        public static string edit_selection {
            get {
                return ResourceManager.GetString("edit-selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to exit app.
        /// </summary>
        public static string esc_to_exit {
            get {
                return ResourceManager.GetString("esc-to-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Picture-in-Picture mode.
        /// </summary>
        public static string exit_picture_in_picture {
            get {
                return ResourceManager.GetString("exit-picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite external app.
        /// </summary>
        public static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied to clipboard.
        /// </summary>
        public static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File moved to the Recycle Bin.
        /// </summary>
        public static string file_moved_to_trash {
            get {
                return ResourceManager.GetString("file-moved-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File properties.
        /// </summary>
        public static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reloaded.
        /// </summary>
        public static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip horizontal.
        /// </summary>
        public static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vertical.
        /// </summary>
        public static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameless mode.
        /// </summary>
        public static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From clipboard.
        /// </summary>
        public static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From &quot;{0}&quot;.
        /// </summary>
        public static string from_format {
            get {
                return ResourceManager.GetString("from-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path.
        /// </summary>
        public static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show cursor in fullscreen.
        /// </summary>
        public static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us translate this app.
        /// </summary>
        public static string help_us_translate_app {
            get {
                return ResourceManager.GetString("help-us-translate-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copied to clipboard.
        /// </summary>
        public static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image info.
        /// </summary>
        public static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image pasted from clipboard.
        /// </summary>
        public static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse and keyboard.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now.
        /// </summary>
        public static string install_now {
            get {
                return ResourceManager.GetString("install-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string landscape_orientation {
            get {
                return ResourceManager.GetString("landscape-orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left arrow.
        /// </summary>
        public static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain aspect ratio.
        /// </summary>
        public static string maintain_aspect_ratio {
            get {
                return ResourceManager.GetString("maintain-aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin bounds.
        /// </summary>
        public static string margin_bounds {
            get {
                return ResourceManager.GetString("margin-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        public static string margins {
            get {
                return ResourceManager.GetString("margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megapixels.
        /// </summary>
        public static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory error.
        /// </summary>
        public static string memory_error {
            get {
                return ResourceManager.GetString("memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        public static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More plugins.
        /// </summary>
        public static string more_plugins {
            get {
                return ResourceManager.GetString("more-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel scroll action.
        /// </summary>
        public static string mouse_wheel_action {
            get {
                return ResourceManager.GetString("mouse-wheel-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move file to the Recycle Bin.
        /// </summary>
        public static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new-version-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window.
        /// </summary>
        public static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new empty window.
        /// </summary>
        public static string new_window_desc {
            get {
                return ResourceManager.GetString("new-window-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in folder.
        /// </summary>
        public static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in 1 second.
        /// </summary>
        public static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image in {0} seconds.
        /// </summary>
        public static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next / previous image in folder.
        /// </summary>
        public static string next_prev_image {
            get {
                return ResourceManager.GetString("next-prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        public static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to open.
        /// </summary>
        public static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not saved.
        /// </summary>
        public static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with external app.
        /// </summary>
        public static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder recursively.
        /// </summary>
        public static string open_recursive {
            get {
                return ResourceManager.GetString("open-recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose app to open.
        /// </summary>
        public static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with custom app.
        /// </summary>
        public static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with default app.
        /// </summary>
        public static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Quick Picture Viewer.
        /// </summary>
        public static string open_with_qpv {
            get {
                return ResourceManager.GetString("open-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        public static string original_size {
            get {
                return ResourceManager.GetString("original-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste image.
        /// </summary>
        public static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file permanently.
        /// </summary>
        public static string perm_delete {
            get {
                return ResourceManager.GetString("perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture-in-Picture mode.
        /// </summary>
        public static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        public static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open an image to view or edit.
        /// </summary>
        public static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin manager.
        /// </summary>
        public static string plugin_manager {
            get {
                return ResourceManager.GetString("plugin-manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory not found.
        /// </summary>
        public static string plugin_not_found {
            get {
                return ResourceManager.GetString("plugin-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin website.
        /// </summary>
        public static string plugin_website {
            get {
                return ResourceManager.GetString("plugin-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string presets {
            get {
                return ResourceManager.GetString("presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to exit fullscreen mode.
        /// </summary>
        public static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image in folder.
        /// </summary>
        public static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print / Export to PDF.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print configuration.
        /// </summary>
        public static string print_conf {
            get {
                return ResourceManager.GetString("print-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set document margins.
        /// </summary>
        public static string print_margins_error {
            get {
                return ResourceManager.GetString("print-margins-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print size.
        /// </summary>
        public static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        public static string ready_to_install {
            get {
                return ResourceManager.GetString("ready-to-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload file.
        /// </summary>
        public static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload plugin list.
        /// </summary>
        public static string reload_plugins {
            get {
                return ResourceManager.GetString("reload-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize SVG.
        /// </summary>
        public static string resize_svg {
            get {
                return ResourceManager.GetString("resize-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App restart required.
        /// </summary>
        public static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore last window bounds.
        /// </summary>
        public static string restore_last_window_bounds {
            get {
                return ResourceManager.GetString("restore-last-window-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right arrow.
        /// </summary>
        public static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 180°.
        /// </summary>
        public static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate counter-clockwise.
        /// </summary>
        public static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate clockwise.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up / down.
        /// </summary>
        public static string scroll_up_down {
            get {
                return ResourceManager.GetString("scroll-up-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection tool.
        /// </summary>
        public static string selection_tool {
            get {
                return ResourceManager.GetString("selection-tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default image viewer.
        /// </summary>
        public static string set_as_default_image_viewer {
            get {
                return ResourceManager.GetString("set-as-default-image-viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as desktop background.
        /// </summary>
        public static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set background.
        /// </summary>
        public static string set_background {
            get {
                return ResourceManager.GetString("set-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set margins.
        /// </summary>
        public static string set_margins_btn {
            get {
                return ResourceManager.GetString("set-margins-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file in explorer.
        /// </summary>
        public static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show navigation arrows.
        /// </summary>
        public static string show_nav_arrows {
            get {
                return ResourceManager.GetString("show-nav-arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show slideshow counter.
        /// </summary>
        public static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show status bar.
        /// </summary>
        public static string show_status_bar {
            get {
                return ResourceManager.GetString("show-status-bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toolbar.
        /// </summary>
        public static string show_toolbar {
            get {
                return ResourceManager.GetString("show-toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string skip_this_version {
            get {
                return ResourceManager.GetString("skip-this-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        public static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        public static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unsaved data will be lost. Are you sure you want to close the application?.
        /// </summary>
        public static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this file?.
        /// </summary>
        public static string sure_perm_delete {
            get {
                return ResourceManager.GetString("sure-perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching time.
        /// </summary>
        public static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string tile {
            get {
                return ResourceManager.GetString("tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation by.
        /// </summary>
        public static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        public static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file.
        /// </summary>
        public static string unable_open_file {
            get {
                return ResourceManager.GetString("unable-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file, file skipped.
        /// </summary>
        public static string unable_open_file_skipped {
            get {
                return ResourceManager.GetString("unable-open-file-skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run external app.
        /// </summary>
        public static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string unsaved_changes {
            get {
                return ResourceManager.GetString("unsaved-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image has unsaved changes. What would you like to do?.
        /// </summary>
        public static string unsaved_changes_question {
            get {
                return ResourceManager.GetString("unsaved-changes-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported pixel format.
        /// </summary>
        public static string unsupported_pixel_format {
            get {
                return ResourceManager.GetString("unsupported-pixel-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version {0} for Quick Picture Viewer is available, you&apos;re using version {1}, update now?.
        /// </summary>
        public static string update_text {
            get {
                return ResourceManager.GetString("update-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Quick Picture Viewer.
        /// </summary>
        public static string updating_qpv {
            get {
                return ResourceManager.GetString("updating-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system setting.
        /// </summary>
        public static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        public static string whats_new {
            get {
                return ResourceManager.GetString("whats-new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in / out.
        /// </summary>
        public static string zoom_in_out {
            get {
                return ResourceManager.GetString("zoom-in-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to actual size.
        /// </summary>
        public static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
