//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quick_picture_viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckboardBackground {
            get {
                return ((bool)(this["CheckboardBackground"]));
            }
            set {
                this["CheckboardBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCursorInFullscreen {
            get {
                return ((bool)(this["ShowCursorInFullscreen"]));
            }
            set {
                this["ShowCursorInFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupPaste {
            get {
                return ((bool)(this["StartupPaste"]));
            }
            set {
                this["StartupPaste"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\System32\\mspaint.exe")]
        public string FavoriteExternalApp {
            get {
                return ((string)(this["FavoriteExternalApp"]));
            }
            set {
                this["FavoriteExternalApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackColor {
            get {
                return ((string)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SlideshowTime {
            get {
                return ((int)(this["SlideshowTime"]));
            }
            set {
                this["SlideshowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SlideshowCounter {
            get {
                return ((bool)(this["SlideshowCounter"]));
            }
            set {
                this["SlideshowCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EscToExit {
            get {
                return ((bool)(this["EscToExit"]));
            }
            set {
                this["EscToExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MouseWheelScrollAction {
            get {
                return ((int)(this["MouseWheelScrollAction"]));
            }
            set {
                this["MouseWheelScrollAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupMaximize {
            get {
                return ((bool)(this["StartupMaximize"]));
            }
            set {
                this["StartupMaximize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupRestoreBounds {
            get {
                return ((bool)(this["StartupRestoreBounds"]));
            }
            set {
                this["StartupRestoreBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 485")]
        public global::System.Drawing.Size StartupWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["StartupWindowSize"]));
            }
            set {
                this["StartupWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point StartupWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["StartupWindowLocation"]));
            }
            set {
                this["StartupWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PipOpacity {
            get {
                return ((double)(this["PipOpacity"]));
            }
            set {
                this["PipOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatusBar {
            get {
                return ((bool)(this["ShowStatusBar"]));
            }
            set {
                this["ShowStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolbar {
            get {
                return ((bool)(this["ShowToolbar"]));
            }
            set {
                this["ShowToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SkippedVersion {
            get {
                return ((string)(this["SkippedVersion"]));
            }
            set {
                this["SkippedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNavArrows {
            get {
                return ((bool)(this["ShowNavArrows"]));
            }
            set {
                this["ShowNavArrows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAENRdWlja0xpYnJhcnksIFZlcnNpb249Mi41LjYuMCwgQ3VsdHVyZ" +
            "T1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsBwEAAAAAAQAAAAEAAAAEF1F1aWNrTGlicmFyeS5Qb" +
            "HVnaW5JbmZvAgAAAAkDAAAABQMAAAAXUXVpY2tMaWJyYXJ5LlBsdWdpbkluZm8KAAAABG5hbWUHdmVyc" +
            "2lvbgV0aXRsZQtkZXNjcmlwdGlvbgRsaW5rB2F1dGhvcnMGYXBpVmVyCWlucHV0VHlwZQdkbGxUeXBlC" +
            "WZ1bmN0aW9ucwEBAQQBBAABAQQnUXVpY2tMaWJyYXJ5LlBsdWdpbkluZm8rTXVsdGlsYW5nU3RyaW5nA" +
            "gAAACBRdWlja0xpYnJhcnkuUGx1Z2luSW5mbytBdXRob3JbXQIAAAAIIlF1aWNrTGlicmFyeS5QbHVna" +
            "W5JbmZvK0Z1bmN0aW9uW10CAAAAAgAAAAYEAAAAC3Fwdi1wbHVnaW5zBgUAAAAFMS4yLjQGBgAAAAtRU" +
            "FYgUGx1Z2lucwX5////J1F1aWNrTGlicmFyeS5QbHVnaW5JbmZvK011bHRpbGFuZ1N0cmluZwYAAAACZ" +
            "W4CY24CZnICaHUCcnUCZXMBAQEBAQECAAAABggAAAAbU2V0IG9mIHByZWluc3RhbGxlZCBwbHVnaW5zB" +
            "gkAAAAV5LiA57uE6aKE6KOF55qE5o+S5Lu2BgoAAAAlVW4gZW5zZW1ibGUgZGUgcGx1Z2lucyBwcsOpa" +
            "W5zdGFsbMOpcwYLAAAAK0VsxZFyZSB0ZWxlcMOtdGV0dCBixZF2w610bcOpbnllayBrw6lzemxldGUGD" +
            "AAAAD7QndCw0LHQvtGAINC/0YDQtdC00YPRgdGC0LDQvdC+0LLQu9C10L3QvdGL0YUg0L/Qu9Cw0LPQu" +
            "NC90L7QsgYNAAAAJkNvbmp1bnRvIGRlIGNvbXBsZW1lbnRvcyBwcmVpbnN0YWxhZG9zBg4AAAAoaHR0c" +
            "HM6Ly9naXRodWIuY29tL01vZHVsZUFydC9xcHYtcGx1Z2lucwkPAAAABAAAAAYQAAAABmJpdG1hcAYRA" +
            "AAABmNzaGFycAkSAAAABw8AAAAAAQAAAAEAAAAEHlF1aWNrTGlicmFyeS5QbHVnaW5JbmZvK0F1dGhvc" +
            "gIAAAAF7f///x5RdWlja0xpYnJhcnkuUGx1Z2luSW5mbytBdXRob3ICAAAABG5hbWUEbGluawEBAgAAA" +
            "AYUAAAAB0JlZWxpbmsGFQAAABpodHRwczovL2dpdGh1Yi5jb20vQmVlbGluawcSAAAAAAEAAAAFAAAAB" +
            "CBRdWlja0xpYnJhcnkuUGx1Z2luSW5mbytGdW5jdGlvbgIAAAAF6v///yBRdWlja0xpYnJhcnkuUGx1Z" +
            "2luSW5mbytGdW5jdGlvbgcAAAAEbmFtZQV0aXRsZQR0eXBlDWlucHV0UmVxdWlyZWQGZGlhbG9nDGhpZ" +
            "GVNYWluRm9ybQZob3RrZXkBBAEAAAAEJ1F1aWNrTGlicmFyeS5QbHVnaW5JbmZvK011bHRpbGFuZ1N0c" +
            "mluZwIAAAABAQEeUXVpY2tMaWJyYXJ5LlBsdWdpbkluZm8rSG90a2V5AgAAAAIAAAAGFwAAAARibHVyA" +
            "ej////5////BhkAAAAQQmx1ciBvciBwaXhlbGF0ZQYaAAAAEuaooeeziuaIluWDj+e0oOWMlgYbAAAAE" +
            "UZsb3Ugb3UgcGl4ZWxpc2VyBhwAAAAYRWxtb3PDs2RvdHQgdmFneSBwaXhlbGVzBh0AAAAw0KDQsNC30" +
            "LzRi9GC0LjQtSDQuNC70Lgg0L/QuNC60YHQtdC70LjQt9Cw0YbQuNGPBh4AAAAURGVzZW5mb2NhciBvI" +
            "HBpeGVsYXIGHwAAAAZlZmZlY3QBAQAF4P///x5RdWlja0xpYnJhcnkuUGx1Z2luSW5mbytIb3RrZXkEA" +
            "AAABGN0cmwFc2hpZnQDYWx0A2tleQAAAAABAQEIAgAAAAEBAEIAAAAB3////+r///8GIgAAAAlncmF5c" +
            "2NhbGUB3f////n///8GJAAAAAlHcmF5c2NhbGUGJQAAAAbngbDpmLYGJgAAAA9OaXZlYXV4IGRlIGdya" +
            "XMGJwAAABJTesO8cmtlw6FybnlhbGF0b3MGKAAAABvQntGC0YLQtdC90LrQuCDRgdC10YDQvtCz0L4GK" +
            "QAAABBFc2NhbGEgZGUgZ3Jpc2VzBioAAAAGZWZmZWN0AQAAAdX////g////AAABRwAAAAHU////6v///" +
            "wYtAAAABmludmVydAHS////+f///wYvAAAADUludmVydCBjb2xvcnMGMAAAAAzlj43ovazpopzoibIGM" +
            "QAAABVJbnZlcnNlciBsZXMgY291bGV1cnMGMgAAAA5JbnZlcnQgc3rDrW5lawYzAAAAJdCY0L3QstC10" +
            "YDRgtC40YDQvtCy0LDRgtGMINGG0LLQtdGC0LAGNAAAABNDYXB0dXJhIGRlIHBhbnRhbGxhBjUAAAAGZ" +
            "WZmZWN0AQAAAcr////g////AQEASQAAAAHJ////6v///wY4AAAAB3JhaW5ib3cBx/////n///8GOgAAA" +
            "AdSYWluYm93BjsAAAAG5b2p6Jm5BjwAAAALQXJjLWVuLWNpZWwGPQAAAAxTeml2w6FydsOhbnkGPgAAA" +
            "AzQoNCw0LTRg9Cz0LAGPwAAAAlBcmNvw61yaXMGQAAAAAZlZmZlY3QBAAABv////+D///8AAAFSAAAAA" +
            "b7////q////BkMAAAAKc2NyZWVuc2hvdAG8////+f///wZFAAAAClNjcmVlbnNob3QGRgAAAAbmiKrls" +
            "Y8GRwAAABBDYXB0dXJlIGQnw6ljcmFuBkgAAAAMUGlsbGFuYXRrw6lwBkkAAAAQ0KHQutGA0LjQvdGI0" +
            "L7RggZKAAAAE0NhcHR1cmEgZGUgcGFudGFsbGEGSwAAAAR0b29sAAABAbT////g////AAAAewAAAAs=")]
        public string PluginsCache {
            get {
                return ((string)(this["PluginsCache"]));
            }
            set {
                this["PluginsCache"] = value;
            }
        }
    }
}
